'use strict';
const express=require('express');
const fs=require('fs');const fsp=fs.promises;const path=require('path');const os=require('os');const{spawn}=require('child_process');
const app=express();
const HOST=process.env.WORKBENCH_HOST||'127.0.0.1',PORT=Number(process.env.WORKBENCH_PORT||8787);
const ROOT=path.resolve(process.env.WORKBENCH_DIR||path.join(os.homedir(),'workbench-projects'));
const CFGDIR=path.join(os.homedir(),'.tablet-workbench'),CFG=path.join(CFGDIR,'config.json'),CACHE=path.join(CFGDIR,'run-cache'),APP=__dirname;
app.use(express.json({limit:'4mb'}));
app.use(express.static(path.join(APP,'public')));
app.use('/vendor/monaco',express.static(path.join(APP,'node_modules','monaco-editor','min','vs')));
const safe=(p='')=>{const r=path.resolve(ROOT,String(p).replace(/^\/+/,''));if(r!==ROOT&&!r.startsWith(ROOT+path.sep))throw Error('Path escapes workspace');return r};
const rel=p=>path.relative(ROOT,p).split(path.sep).join('/');
async function init(){await Promise.all([fsp.mkdir(ROOT,{recursive:true}),fsp.mkdir(CACHE,{recursive:true}),fsp.mkdir(CFGDIR,{recursive:true})]);const m=path.join(ROOT,'.workbench-initialized');if(!fs.existsSync(m)){for(const n of await fsp.readdir(path.join(APP,'examples'))){const d=path.join(ROOT,n);if(!fs.existsSync(d))await fsp.copyFile(path.join(APP,'examples',n),d)}await fsp.writeFile(m,'ok\n')}}
async function tree(d=ROOT,depth=0){if(depth>10)return[];const es=(await fsp.readdir(d,{withFileTypes:true})).filter(e=>!['.git','node_modules','.workbench-initialized'].includes(e.name));es.sort((a,b)=>Number(b.isDirectory())-Number(a.isDirectory())||a.name.localeCompare(b.name));const out=[];for(const e of es){const a=path.join(d,e.name);out.push(e.isDirectory()?{type:'dir',name:e.name,path:rel(a),children:await tree(a,depth+1)}:{type:'file',name:e.name,path:rel(a)})}return out}
async function cfg(){const d={apiKey:'',model:'deepseek-v4-flash',thinking:false,baseUrl:'https://api.deepseek.com',systemPrompt:'You are a coding assistant inside a lightweight tablet IDE. Be concise and prioritize working code.'};try{return{...d,...JSON.parse(await fsp.readFile(CFG,'utf8'))}}catch{return d}}
const run=(cmd,args,cwd,timeout=20000)=>new Promise(ok=>{const p=spawn(cmd,args,{cwd,env:process.env});let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);const t=setTimeout(()=>p.kill('SIGKILL'),timeout);p.on('error',e=>ok({code:-1,stdout:out,stderr:err+e.message}));p.on('close',c=>{clearTimeout(t);ok({code:c??-1,stdout:out,stderr:err})})});
function parseMarkers(text){const lines=String(text||'').split(/\r?\n/);const out=[];for(const s of lines){let m=s.match(/:(\d+):(\d+):\s*(warning|error|note)?:?\s*(.*)$/i);if(!m)m=s.match(/line\s+(\d+)(?:,\s*column\s+(\d+))?.*?(SyntaxError|Error):\s*(.*)$/i);if(m){const sev=/warn/i.test(m[3]||'')?'warning':'error';out.push({line:Number(m[1])||1,column:Number(m[2])||1,severity:sev,message:(m[4]||s).trim()})}}if(!out.length&&String(text||'').trim())out.push({line:1,column:1,severity:'error',message:String(text).trim().slice(0,1200)});return out.slice(0,50)}
app.get('/api/info',(_q,r)=>r.json({workspace:ROOT,host:HOST,port:PORT,version:'0.2.0'}));
app.get('/api/tree',async(_q,r)=>{try{r.json(await tree())}catch(e){r.status(500).json({error:e.message})}});
app.get('/api/file',async(q,r)=>{try{r.type('text/plain').send(await fsp.readFile(safe(q.query.path),'utf8'))}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/file',async(q,r)=>{try{const a=safe(q.body.path);await fsp.mkdir(path.dirname(a),{recursive:true});await fsp.writeFile(a,String(q.body.content??''),'utf8');r.json({ok:true})}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/fs/new',async(q,r)=>{try{const a=safe(q.body.path);if(fs.existsSync(a))throw Error('Already exists');q.body.type==='dir'?await fsp.mkdir(a,{recursive:true}):(await fsp.mkdir(path.dirname(a),{recursive:true}),await fsp.writeFile(a,''));r.json({ok:true})}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/fs/delete',async(q,r)=>{try{await fsp.rm(safe(q.body.path),{recursive:true,force:true});r.json({ok:true})}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/config',async(_q,r)=>{const c=await cfg();r.json({hasApiKey:!!c.apiKey,maskedKey:c.apiKey?c.apiKey.slice(0,4)+'••••'+c.apiKey.slice(-4):'',model:c.model,thinking:c.thinking,baseUrl:c.baseUrl,systemPrompt:c.systemPrompt})});
app.post('/api/config',async(q,r)=>{try{const o=await cfg(),n={...o,apiKey:String(q.body.apiKey||'').trim()||o.apiKey,model:q.body.model||o.model,thinking:!!q.body.thinking,baseUrl:String(q.body.baseUrl||o.baseUrl).replace(/\/$/,''),systemPrompt:String(q.body.systemPrompt||o.systemPrompt)};await fsp.writeFile(CFG,JSON.stringify(n,null,2),{mode:0o600});r.json({ok:true})}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/chat',async(q,r)=>{try{const c=await cfg();if(!c.apiKey)return r.status(400).json({error:'Configure DeepSeek API key first.'});const msgs=[{role:'system',content:c.systemPrompt}];if(q.body.includeFile&&q.body.activeFile)msgs.push({role:'system',content:`Current file: ${q.body.activeFile.path}\n\n${String(q.body.activeFile.content||'').slice(0,50000)}`});for(const m of(q.body.messages||[]).slice(-30))if(['user','assistant'].includes(m.role))msgs.push({role:m.role,content:String(m.content||'')});const b={model:c.model,messages:msgs,stream:false,thinking:{type:c.thinking?'enabled':'disabled'},max_tokens:8192};const x=await fetch(c.baseUrl+'/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+c.apiKey},body:JSON.stringify(b)}),d=await x.json().catch(()=>({}));if(!x.ok)return r.status(x.status).json({error:d?.error?.message||`HTTP ${x.status}`});r.json({answer:d?.choices?.[0]?.message?.content||'',model:d.model||c.model})}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/diagnose',async(q,r)=>{try{const a=safe(q.body.path),cwd=path.dirname(a),content=String(q.body.content??''),ext=path.extname(a).toLowerCase();await fsp.writeFile(a,content,'utf8');let cmd=null;if(ext==='.py')cmd=['python',['-m','py_compile',a]];else if(ext==='.c')cmd=['clang',['-fsyntax-only',a]];else if(['.cc','.cpp','.cxx'].includes(ext))cmd=['clang++',['-std=c++17','-fsyntax-only',a]];else if(ext==='.rs')cmd=['rustc',['--emit=metadata','--out-dir',CACHE,a]];else if(ext==='.go')cmd=['go',['test',a]];else if(ext==='.java')cmd=['javac',['-d',CACHE,a]];else if(ext==='.sh')cmd=['bash',['-n',a]];else return r.json({supported:false,markers:[]});const x=await run(cmd[0],cmd[1],cwd,10000);r.json({supported:true,markers:x.code===0?[]:parseMarkers((x.stderr||'')+(x.stdout||'')),raw:(x.stderr||'')+(x.stdout||'')})}catch(e){r.json({supported:true,markers:[{line:1,column:1,severity:'error',message:e.message}],raw:e.message})}});
app.post('/api/run',async(q,r)=>{try{const a=safe(q.body.path),cwd=path.dirname(a);await fsp.writeFile(a,String(q.body.content??''));const e=path.extname(a).toLowerCase(),bin=path.join(CACHE,Buffer.from(rel(a)).toString('hex').slice(0,50));let one,two=null;if(e==='.py')one=['python',[a]];else if(['.js','.mjs','.cjs'].includes(e))one=['node',[a]];else if(['.ts','.tsx'].includes(e))one=[path.join(APP,'node_modules','.bin','tsx'),[a]];else if(e==='.sh')one=['bash',[a]];else if(e==='.c'){one=['clang',[a,'-O0','-o',bin]];two=[bin,[]]}else if(['.cc','.cpp','.cxx'].includes(e)){one=['clang++',[a,'-std=c++17','-O0','-o',bin]];two=[bin,[]]}else if(e==='.rs'){one=['rustc',[a,'-o',bin]];two=[bin,[]]}else if(e==='.go')one=['go',['run',a]];else if(e==='.java'){one=['javac',[a]];two=['java',['-cp',cwd,path.basename(a,'.java')]]}else if(e==='.html')return r.json({code:0,stdout:'Use Preview for HTML.\n',preview:'/preview/'+encodeURI(rel(a))});else throw Error('This file type is not configured.');const x=await run(one[0],one[1],cwd);if(x.code!==0||!two)return r.json(x);const y=await run(two[0],two[1],cwd);r.json({code:y.code,stdout:x.stdout+y.stdout,stderr:x.stderr+y.stderr})}catch(e){r.status(400).json({error:e.message})}});
app.get('/preview/*',(q,r)=>{try{r.sendFile(safe(decodeURI(q.params[0]||'')))}catch(e){r.status(404).send(e.message)}});
init().then(()=>app.listen(PORT,HOST,()=>console.log(`SuKoYa Tablet Workbench v0.2: http://${HOST}:${PORT}\nWorkspace: ${ROOT}`))).catch(e=>{console.error(e);process.exit(1)});
